name: algo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - numpy
      - aiohttp
      - websockets
      - pyyaml
      - textblob
      - nltk
      - pytest
      - flake8
